// Pulls in the ESLint config Nuxt generates from your modules and options
// (see the `eslint` key in nuxt.config.ts). Regenerated by `nuxt prepare`.
import withNuxt from './.nuxt/eslint.config.mjs'

export default withNuxt({
  rules: {
    // Formatting is Prettier's job; keep ESLint focused on logic. These Vue
    // stylistic rules overlap with formatting, so turn them off to avoid
    // conflicts and noise.
    'vue/attributes-order': 'off',
    'vue/html-self-closing': 'off',
  },
})
